capstone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('map.urls')),
]

map/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('user/<str:username>', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),
    path('state/<str:state>', views.state, name='state'),
    path('trips', views.trips, name='trips'),

    # API Routes
    path('api/states', views.api_states, name='api_states'),
    path('api/trip', views.api_newtrip, name='api_newtrip'),
    path('api/trip/<int:id>', views.api_trip, name='api_trip'),
    path('api/username/<str:username>', views.api_username, name='api_username')
]

map/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.

class User(AbstractUser):
    states = models.ManyToManyField('State', through='Trip')
    trips_per_page = models.SmallIntegerField(
        default=10,
        validators=[
            MinValueValidator(5),
            MaxValueValidator(100)
        ]
    )

class State(models.Model):

    REGIONS = [
        ('W', 'West'),
        ('MW', 'Midwest'),
        ('NE', 'Northeast'),
        ('SW', 'Southwest'),
        ('SE', 'Southeast')
    ]

    name = models.CharField(max_length=14)
    code = models.CharField(max_length=2)
    region = models.CharField(max_length=2, choices=REGIONS)

    class Meta:
       ordering = ['name']

    def __str__(self):
        return f"{self.name}"


class Trip(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='trips')
    location = models.CharField(max_length=50)
    state = models.ForeignKey('State', on_delete=models.RESTRICT, related_name='trips')
    description = models.TextField(blank=True, null=True)
    date1 = models.DateField(blank=True, null=True)
    date2 = models.DateField(blank=True, null=True)

    class Meta:
       ordering = ['-date1', '-pk']

    def serialize(self):
        return {
            "id": self.pk,
            "location": self.location,
            "state": self.state.code,
            "description": self.description,
            "date1": self.date1,
            "date2": self.date2
        }

    def __str__(self):
        return f"{self.location}, {self.state}"


class Achievement(models.Model):
    slug = models.SlugField(max_length=15)
    icon = models.SlugField(max_length=20)
    color = models.SlugField(max_length=10)
    title = models.CharField(max_length=15)
    description = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.title} ({self.slug})"

map/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from markdown2 import markdown

from .models import User, State, Trip, Achievement

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        trips = Trip.objects.filter(user=request.user)
    else:
        trips = None
    w_states = State.objects.filter(region='W')
    mw_states = State.objects.filter(region='MW')
    ne_states = State.objects.filter(region='NE')
    sw_states = State.objects.filter(region='SW')
    se_states = State.objects.filter(region='SE')


    return render(request, 'map/index.html', {
        "trips": trips,
        "w_states": w_states,
        "mw_states": mw_states,
        "ne_states": ne_states,
        "sw_states": sw_states,
        "se_states": se_states
    })


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        if password != password_confirmation:
            return render(request, 'map/login.html', {
                'message': "Passwords don't match.",
                'registration': True
            })
        try:
            user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name)
            user.save()
        except IntegrityError:
            return render(request, 'map/login.html', {
                'message': "Username not available.",
                'registration': True
            })
        login(request, user)
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'map/login.html', {
            'registration': True
        })


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, 'map/login.html', {
                'message': "Invalid username and/or password.",
                'registration': False
            })
    else:
        return render(request, 'map/login.html', {
            'registration': False
        })


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def profile(request, username):
    profile = User.objects.get(username=username)

    trips = Trip.objects.filter(user=profile)
    visited_states = set()
    for trip in trips:
        visited_states.add(trip.state)

    state_num = len(visited_states)
    progress = state_num / 50 * 100;

    states_to_visit = set()

    for state in State.objects.all():
        if state not in visited_states:
            states_to_visit.add(state)

    # Achievements
    achievements = set()

    if trips.count() >= 1:
        achievements.add(Achievement.objects.get(slug='first-trip'))

    if state_num >= 10:
        achievements.add(Achievement.objects.get(slug='ten-states'))

    if state_num >= 20:
        achievements.add(Achievement.objects.get(slug='twenty-states'))

    if state_num >= 30:
        achievements.add(Achievement.objects.get(slug='thirty-states'))

    if state_num >= 40:
        achievements.add(Achievement.objects.get(slug='forty-states'))

    if state_num == 50:
        achievements.add(Achievement.objects.get(slug='all-states'))

    if State.objects.get(code='HI') in visited_states:
        achievements.add(Achievement.objects.get(slug='aloha'))

    for trip in trips:
        if trip.state == State.objects.get(code='AK'):
            if trip.date1 != None:
                if trip.date1.month in [12, 1, 2, 3]:
                    achievements.add(Achievement.objects.get(slug='freezing'))
            if trip.date2 != None:
                if trip.date2.month in [12, 1, 2, 3]:
                    achievements.add(Achievement.objects.get(slug='freezing'))

        if trip.state == State.objects.get(code='AZ'):
            if trip.date1 != None:
                if trip.date1.month in [6, 7, 8, 9]:
                    achievements.add(Achievement.objects.get(slug='dry-heat'))
            if trip.date2 != None:
                if trip.date2.month in [6, 7, 8, 9]:
                    achievements.add(Achievement.objects.get(slug='dry-heat'))

    return render(request, 'map/profile.html', {
        "profile": profile,
        "visited_states": visited_states,
        "state_num": state_num,
        "states_to_visit": states_to_visit,
        "progress": progress,
        "achievements": achievements
    })


@login_required
def settings(request):
    profile = User.objects.get(pk=request.user.pk)

    if request.method == "GET":
        return render(request, 'map/settings.html', {
            "profile": profile
        })

    if request.method == "POST":
        section = request.POST["section"]

        if section == 'profile':
            # Username validation
            new_username = request.POST["username"]
            if new_username != profile.username and User.objects.filter(username=new_username).exists():
                return render(request, 'map/settings.html', {
                        "profile": profile,
                        "message": "Username not available.",
                        "message_status": 'danger'
                    })
            elif new_username != profile.username:
                profile.username = new_username

            new_email = request.POST["email"]
            new_first_name = request.POST["first_name"]
            new_last_name = request.POST["last_name"]

            profile.email = new_email
            profile.first_name = new_first_name
            profile.last_name = new_last_name

            profile.save()
            login(request, profile)

            return render(request, 'map/settings.html', {
                "profile": profile,
                "message": 'Profile updated.',
                "message_status": 'success'
            })

        elif section == 'password':
            # Passwords validation
            new_password = request.POST["new_password"]
            confirm_password = request.POST["confirm_password"]
            if new_password != '' and new_password != confirm_password:
                return render(request, 'map/settings.html', {
                    "profile": profile,
                    "message": "Passwords don't match.",
                    "message_status": 'danger'
                })
            elif new_password != '':
                profile.set_password(new_password)
                profile.save()
                login(request, profile)
                return render(request, 'map/settings.html', {
                    "profile": profile,
                    "message": 'Password updated.',
                    "message_status": 'success'
                })


        elif section == 'settings':
            trips_per_page = request.POST["trips_per_page"]
            profile.trips_per_page = int(trips_per_page)
            profile.save()

            return render(request, 'map/settings.html', {
                "profile": profile,
                "message": 'Settings updated.',
                "message_status": 'success'
            })

        else:
            return render(request, 'map/settings.html', {
                "profile": profile,
                "message": 'Bad request.',
                "message_status": 'danger'
            })


def state(request, state):
    state_obj = State.objects.get(code=state)
    if request.user.is_authenticated:
        trips = Trip.objects.filter(user=request.user, state=state_obj)
    else:
        trips = None

    try:
        f = default_storage.open(f"states/{state}.md")
        state_info = f.read().decode("utf-8")
    except FileNotFoundError:
        state_info = ''

    return render(request, 'map/state.html', {
        "state": state_obj,
        "state_info": markdown(state_info),
        "trips": trips
    })


# TODO: refresh the page or add trip if trip is added @ my trips (not index)
@login_required
def trips(request):
    profile = User.objects.get(username=request.user)
    trips = Trip.objects.filter(user=profile)
    states = State.objects.all()

    get_location = request.GET.get('loc')
    if get_location != None and get_location != '':
        trips = trips.filter(location__icontains=get_location)

    get_state = request.GET.get('state')
    if get_state != None and get_state != '':
        state_obj = State.objects.get(code=get_state)
        trips = trips.filter(state=state_obj)

    get_date1 = request.GET.get('date1')
    if get_date1 != None and get_date1 != '':
        trips = trips.filter(date1__gte=get_date1)

    get_date2 = request.GET.get('date2')
    if get_date2 != None and get_date2 != '':
        trips = trips.filter(date1__lte=get_date2)

    get_sort = request.GET.get('sort')
    if get_sort == 'asc':
        trips = trips.reverse()

    paginator = Paginator(trips, profile.trips_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'map/trips.html', {
        "profile": profile,
        "states": states,
        "get_location": get_location,
        "get_state": get_state,

map/templates/map/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" rel="stylesheet">
        <link href="{% static 'map/styles.css' %}" rel="stylesheet">
        <title>US Travel Tracker - {% block title %}{% endblock %}</title>
    </head>
    <body>

        {% if user.is_authenticated %}
        <div id="alert"></div>

        <!-- Add Trip Modal -->
        <div class="modal fade" id="addTripModal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="addTripModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add Trip</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">

                    <!-- Add trip inputs START -->
                    <div class="row my-3">
                        <div class="col">
                            <input class="form-control" type="text" id="location" name="location" placeholder="Location (required)" maxlength="50" required>
                        </div>
                    </div>
                    <div class="row my-3">
                        <div class="col">
                            <select class="form-select" id="state" name="state" required>
                                <option selected disabled hidden>State (required)</option>
                                <option value="AL">Alabama</option>
                                <option value="AK">Alaska</option>
                                <option value="AZ">Arizona</option>
                                <option value="AR">Arkansas</option>
                                <option value="CA">California</option>
                                <option value="CO">Colorado</option>
                                <option value="CT">Connecticut</option>
                                <option value="DE">Delaware</option>
                                <option value="FL">Florida</option>
                                <option value="GA">Georgia</option>
                                <option value="HI">Hawaii</option>
                                <option value="ID">Idaho</option>
                                <option value="IL">Illinois</option>
                                <option value="IN">Indiana</option>
                                <option value="IA">Iowa</option>
                                <option value="KS">Kansas</option>
                                <option value="KY">Kentucky</option>
                                <option value="LA">Louisiana</option>
                                <option value="ME">Maine</option>
                                <option value="MD">Maryland</option>
                                <option value="MA">Massachusetts</option>
                                <option value="MI">Michigan</option>
                                <option value="MN">Minnesota</option>
                                <option value="MS">Mississippi</option>
                                <option value="MO">Missouri</option>
                                <option value="MT">Montana</option>
                                <option value="NE">Nebraska</option>
                                <option value="NV">Nevada</option>
                                <option value="NH">New Hampshire</option>
                                <option value="NJ">New Jersey</option>
                                <option value="NM">New Mexico</option>
                                <option value="NY">New York</option>
                                <option value="NC">North Carolina</option>
                                <option value="ND">North Dakota</option>
                                <option value="OH">Ohio</option>
                                <option value="OK">Oklahoma</option>
                                <option value="OR">Oregon</option>
                                <option value="PA">Pennsylvania</option>
                                <option value="RI">Rhode Island</option>
                                <option value="SC">South Carolina</option>
                                <option value="SD">South Dakota</option>
                                <option value="TN">Tennessee</option>
                                <option value="TX">Texas</option>
                                <option value="UT">Utah</option>
                                <option value="VT">Vermont</option>
                                <option value="VA">Virginia</option>
                                <option value="WA">Washington</option>
                                <option value="WV">West Virginia</option>
                                <option value="WI">Wisconsin</option>
                                <option value="WY">Wyoming</option>
                            </select>
                        </div>
                    </div>
                    <div class="row g-3">
                        <div class="col">
                            <div class="input-group">
                                <span class="input-group-text">From</span>
                                <input class="form-control" id="date1" name="date1" type="date">
                            </div>
                        </div>
                        <div class="col">
                            <div class="input-group">
                                <span class="input-group-text">To</span>
                                <input class="form-control" id="date2" name="date2" type="date">
                            </div>

                        </div>
                    </div>
                    <div class="row my-3">
                        <div class="col">
                            <textarea class="form-control" id="description" name="description" rows="5" placeholder="Brief trip description"></textarea>
                            <div id="form-help" class="form-text">Dates and trip description are optional</div>
                        </div>
                    </div>
                    <!-- Add trip inputs END -->

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" onclick="resetTrip();">Reset</button>
                <button type="button" class="btn btn-primary" onclick="addTrip();">Add Trip</button>
              </div>
            </div>
          </div>
        </div>
        <!-- END Add Trip Modal -->
        {% endif %}

        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-xxl">
                <a class="navbar-brand" href="{% url 'index' %}"><strong>US TRAVEL TRACKER</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-grow-1">
                        {% url 'index' as index_view %}
                        {% url 'trips' as trips_view %}
                        {% url 'profile' user as profile_view %}
                        {% url 'settings' as settings_view %}
                        {% url 'login' as login_view %}
                        {% url 'register' as register_view %}

                        <li class="nav-item {% if not user.is_authenticated %}me-auto{% endif %}"><a class="nav-link {% if request.path == index_view %}active{% endif %}" href="{% url 'index' %}">Map</a></li>

                        {% if user.is_authenticated %}
                            <li class="nav-item me-auto"><a class="nav-link {% if request.path == trips_view %}active{% endif %}" href="{% url 'trips' %}">My Trips</a></li>
                        {% endif %}

                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown me-2 d-flex">
                                <a class="nav-link dropdown-toggle {% if request.path == profile_view or request.path == settings_view %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown"><i class="bi bi-person-circle"></i> {{ user.username }}</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'profile' user.username %}">Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'settings' %}">Settings</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="nav-item me-2 d-flex"><a class="nav-link {% if request.path == login_view or request.path == register_view %}active{% endif %}" href="{% url 'login' %}">Log In / Register</a></li>
                        {% endif %}

                    </ul>
                    {% if not user.is_authenticated %}<span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Log in or register to start tracking your trips">{% endif %}
                        <button class="btn btn-primary {% if not user.is_authenticated %}disabled{% endif %} d-flex" data-bs-toggle="modal" data-bs-target="#addTripModal">Add Trip</button>
                    {% if not user.is_authenticated %}</span>{% endif %}
                </div>
            </div>
        </nav>

        <div class="container-xxl">

            {% block body %}
            {% endblock %}

            <!-- p class="fst-italic text-muted">
                <small>
                    Copyright &copy; {% now "Y" %} — <a href="https://github.com/david-phx" class="text-muted">david-phx</a> as a capstone project for <a href="https://www.edx.org/course/cs50s-web-programming-with-python-and-javascript" class="text-muted">CS50W</a>.
                </small>
            </p -->
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <script src="{% static 'map/script.js' %}"></script>
    </body>
</html>

map/templates/map/login.html
{% extends "map/layout.html" %}
{% load static %}

{% block title %}Login / Register{% endblock %}

{% block body %}

    <div class="row justify-content-center mt-4 mb-3">
        <div class="btn-group col-md-3 col-sm-4" role="group">
            <button type="button" class="btn btn-outline-primary {{ registration|yesno:",active" }}" id="login-switch">Log In</button>
            <button type="button" class="btn btn-outline-primary {{ registration|yesno:"active," }}" id="registration-switch">Register</button>
        </div>
    </div>

    <div class="row justify-content-center">

        <div class="col-md-6">

            {% if message %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}

            <div id="login-wrapper" class="my-3" style="{{ registration|yesno:'display: none;,' }}">
                <form  class="needs-validation" action="{% url 'login' %}" id="login_form" method="post" novalidate>
                    {% csrf_token %}
                    <div class="my-3">
                        <input class="form-control" type="text" name="username" placeholder="Username" required autofocus>
                    </div>
                    <div class="mb-3">
                        <input class="form-control" type="password" name="password" placeholder="Password" required>
                    </div>
                    <input class="btn btn-primary mb-3" type="submit" value="Login">
                </form>

                Don't have an account? <a href="#" id="registration-link"><strong>Register</strong></a>
            </div>

            <div id="registration-wrapper" class="my-3" style="{{ registration|yesno:',display: none;' }}">
                <form class="needs-validation" action="{% url 'register' %}" id="registration_form" method="post" novalidate>
                    {% csrf_token %}
                    <div class="row g-3 mb-3">
                        <div class="col">
                            <input class="form-control" type="text" name="first_name" placeholder="First Name" required autofocus>
                        </div>
                        <div class="col">
                            <input class="form-control" type="text" name="last_name" placeholder="Last Name" required>
                        </div>
                    </div>
                    <div class="my-3">
                        <input class="form-control" type="email" name="email" placeholder="Email Address" required>
                        <div id="email-help" class="form-text">We'll never share your email with anyone else</div>
                    </div>
                    <div class="input-group has-validation">
                        <span class="input-group-text">example.com/user/</span>
                        <input class="form-control" type="text" id="username" name="username" placeholder="Username" oninput="checkUsernameAvailability();" required>
                        <div id="username-feedback" class="invalid-feedback">Username not available</div>
                    </div>
                    <div id="username-help" class="form-text">Letters, numbers, dashes, and periods only, has to start with a letter</div>
                    <div class="my-3">
                        <input class="form-control" type="password" name="password" id="password" placeholder="Password" required>
                    </div>
                    <div class="my-3">
                        <input class="form-control" type="password" name="password_confirmation" id="password_confirmation" placeholder="Confirm Password" oninput="checkMatchingPasswords();" required>
                        <div class="invalid-feedback">Passwords don't match</div>
                    </div>
                    <div class="form-check my-3">
                        <input class="form-check-input" type="checkbox" value="" id="agree" required>
                        <label class="form-check-label" for="agree">
                            I agree to the <a href="#">Terms of Service</a>, <a href="#">Privacy Policy</a>, and <a href="#">Cookies Policy</a>.
                        </label>
                    </div>
                    <input class="btn btn-primary mb-3" type="submit" value="Register">
                </form>

                Already have an account? <a href="#" id="login-link"><strong>Log In</strong></a>
            </div>

        </div>
    </div>

    <script src="{% static 'map/login.js' %}"></script>
{% endblock %}

map/templates/map/state.html
{% extends "map/layout.html" %}
{% load static %}

{% block title %}{{ state.name }}{% endblock %}

{% block body %}

<div class="row justify-content-center my-5">
    <div class="col col-12 col-md-2 border rounded px-4 pb-4 mb-3">
        <img src="{% static 'map/flags/' %}{{ state.code }}.svg" class="img-thumbnail my-3">
        State code: <strong>{{ state.code }}</strong><br>
        Region: <strong>{{ state.get_region_display }}</strong><br>

        {% if user.is_authenticated %}
            <p class="my-4"><a href="{% url 'trips' %}?state={{ state.code }}" >My trips to {{ state.name }}</a></p>
        {% endif %}
    </div>

    <div class="col col-12 col-md-10 px-4 pb-4">
        <h1>{{ state.name }}</h1>

        {{ state_info|safe }}

        {% if user.is_authenticated %}
            <h3>Most Recent Trips to {{ state.name }}</h3>

            <ul>
                {% for trip in trips %}
                    <li>{{ trip.location }} <span class="text-muted">({{ trip.date1 }} &ndash; {{ trip.date2 }})</span></li>
                {% empty %}
                    No recent trips
                {% endfor %}
            </ul>

        {% endif %}
    </div>

</div>

{% endblock %}